node: 1	NumberTargets: 2	NumberSNPs: 1222
LM018
LM088

node: 2	NumberTargets: 3	NumberSNPs: 8088
LM018
LM088
NIH05001

node: 3	NumberTargets: 6	NumberSNPs: 14580
LM018
LM040
LM087
LM088
LM095
NIH05001

node: 4	NumberTargets: 9	NumberSNPs: 0
C_acc_ATCC49725
LM018
LM031
LM040
LM061
LM087
LM088
LM095
NIH05001

node: 5	NumberTargets: 2	NumberSNPs: 0
C_acc_ATCC49725
LM031

node: 6	NumberTargets: 3	NumberSNPs: 6956
LM040
LM087
LM095

node: 7	NumberTargets: 2	NumberSNPs: 7358
LM087
LM095

node: C_acc_ATCC49725	NumberTargets: 1	NumberSNPs: 31
C_acc_ATCC49725

node: LM018	NumberTargets: 1	NumberSNPs: 2113
LM018

node: LM031	NumberTargets: 1	NumberSNPs: 11269
LM031

node: LM040	NumberTargets: 1	NumberSNPs: 9823
LM040

node: LM061	NumberTargets: 1	NumberSNPs: 11487
LM061

node: LM087	NumberTargets: 1	NumberSNPs: 15
LM087

node: LM088	NumberTargets: 1	NumberSNPs: 3165
LM088

node: LM095	NumberTargets: 1	NumberSNPs: 7
LM095

node: NIH05001	NumberTargets: 1	NumberSNPs: 2689
NIH05001

